version: '2'

services:

  collectd:
    build:
      context: collectd/
    networks:
      - elk

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
      - "25826:25826/udp"
    networks:
      - elk

  grafana:
    build:
      context: grafana/
    ports:
      - "3000:3000"
    networks:
      - elk

networks:

  elk:
    driver: bridge
