version: '2'

services:

  collectd:
    build:
      context: collectd/
    volumes:
      - ./collectd/config/collectd.conf:/etc/collectd.conf:ro

  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/config/types.db:/usr/share/collectd/types.db:ro
      - /var/lib/influxdb
    ports:
      - "8086:8086"
      - "25826:25826/udp"

  grafana:
    build:
      context: grafana/
    ports:
      - "3000:3000"
